
CONDOR_HOST = ap.pegasus-ai.org

DAEMON_LIST = MASTER, STARTD

CCB_ADDRESS = $(CONDOR_HOST)
CCB_HEARTBEAT_INTERVAL = 90
PRIVATE_NETWORK_NAME = $(FULL_HOSTNAME)

TRUST_DOMAIN = studio.pegasus-ai.org
FILESYSTEM_DOMAIN = $(HOSTNAME)
UID_DOMAIN = $(HOSTNAME)

# networking settings
UPDATE_COLLECTOR_WITH_TCP = True
USE_TCP_KEEPALIVE = True
TCP_KEEPALIVE_INTERVAL = 60
ENABLE_IPV6 = False
ENABLE_IPV4 = True

# All daemons should log to syslog instead of to their corresponding files.  In this
# container, syslog is configured to echo all logs to stdout (which the container runtime
# should pick up).
MAX_DEFAULT_LOG = 0
ALL_DEBUG=D_CAT,D_SUB_SECOND,D_PID

