
CONDOR_HOST = ap.pegasus-ai.org

DAEMON_LIST = MASTER, STARTD

CCB_ADDRESS = $(CONDOR_HOST)
CCB_HEARTBEAT_INTERVAL = 120
PRIVATE_NETWORK_NAME = $(FULL_HOSTNAME)

TRUST_DOMAIN = studio.pegasus-ai.org
FILESYSTEM_DOMAIN = $(HOSTNAME)
UID_DOMAIN = $(HOSTNAME)

# All daemons should log to syslog instead of to their corresponding files.  In this
# container, syslog is configured to echo all logs to stdout (which the container runtime
# should pick up).
MAX_DEFAULT_LOG = 0
ALL_DEBUG=D_CAT,D_SUB_SECOND,D_PID

